### ISSUE TITLE
Registration - email fields

### ISSUE THREAD

**Issue by matuskrizo** [Wradgio/StretchShop#14]
When I try to register with incorrect email and email conform fields, I get error. This scenario is correct. But when I retype correct email address, error is still there - Values do not match.

**Comment by matuskrizo** [comment]
Aaaand there is something worst - I am logged in. I see error, I don´t get any confirm email and I´m logged in not existing account.

**Comment by Wradgio** [comment]
Please can you write me steps to reproduce. I am having a hard time reproducing it.

**Comment by matuskrizo** [comment]
When I try reproduce this issue, everything works fine now. Maybe is this fixed already.

**Comment by Wradgio** [comment]
Closing - unable to reproduce.
